
std_msgs/Header header       

int32   brakecurfront_stdiag
int32   brakecurrear_stdiag
int32   steercurleft_stdiag
int32   steercurright_stdiag
int32   handbackpilot_stdiag
int32   handfrontpilot_stdiag
int32   handleftpilot_stdiag
int32   handrightpilot_stdiag
int32   vehsteer_angle_stdiag
int32   tricolorbuzzer_stdiag
int32   tricoloryellow_stdiag
int32   tricolorred_stdiag
int32   tricolorgreen_stdiag
