FROM 10.233.88.6:60001/geacx2_aarch64/ubuntu22.04:latest

WORKDIR /home/sany/work

# 仅拷贝编译后的install目录（消息产物）
COPY install ./install

# 创建日志目录，保持目录规范统一
RUN mkdir -p /var/log/ros2/{bridge,control,diagnostics,localization,perception,VLM,VLA,planning,decision}

CMD ["/bin/bash"]
